spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:

        - id: INVENTORY-COMMAND
          uri: http://localhost:9001
          predicates:
            - Path=/inventory/products
            - Method=POST

        - id: INVENTORY-QUERY
          uri: http://localhost:9000
          predicates:
            - Path=/inventory/products
            - Method=GET
      discovery:
        locator:
          enabled: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"