logging:
  file: logs/gateway.production.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    io.github.bhuwanupadhyay: WARN
    org.springframework.cloud.gateway: WARN