#Database Configuration

#spring.datasource.driverClassName=
#spring.datasource.url=jdbc:h2:~/jooq-spring-boot-example
#spring.datasource.username=sa
#spring.datasource.password=
#
#  #jOOQ Configuration
#spring.jooq.sql-dialect=H2
#
#
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/db/ordering_db
    username: sa
    password:
  jooq:
    sql-dialect: h2