/*
 * Inventory
 * API for inventory management
 *
 * OpenAPI spec version: 1.0-snapshot
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.bhuwanupadhyay.inventory.api;

import io.github.bhuwanupadhyay.inventory.invoker.ApiException;
import io.github.bhuwanupadhyay.inventory.model.CreateProductRequest;
import io.github.bhuwanupadhyay.inventory.model.CreateProductResponse;
import io.github.bhuwanupadhyay.inventory.model.ProductResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductApi
 */
@Ignore
public class ProductApiTest {

    private final ProductApi api = new ProductApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void createProductTest() throws ApiException {
        CreateProductRequest createProductRequest = null;
        CreateProductResponse response = api.createProduct(createProductRequest);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void findAllProductsTest() throws ApiException {
        ProductResponse response = api.findAllProducts();

        // TODO: test validations
    }
    
}
