spring:
  application:
    name: configs
  cloud:
    config:
      server:
        git:
          uri: file://${app.root.dir}/microservices
server:
  port: 8888
eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5